<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Camera" Id="{65979892-032e-45c7-85f8-32f178bd09d1}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Camera
VAR
	_IV3 : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="_scanner" Id="{035e3899-2798-4c63-a1c6-9bb0ead59095}">
      <Declaration><![CDATA[METHOD PROTECTED _scanner
VAR_INPUT
	_scanner : BOOL;
	_Keyence : BOOL;
	_Ivana	: BOOL;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Camera">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Camera._scanner">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>